package com.myapp.agent;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.myapp.agent.llm.AgentDecision;
import com.myapp.agent.tool.Tool;
import com.myapp.agent.tool.ToolRegistry;
import com.myapp.model.SessionEntity;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class AgentHelper {

    private final ToolRegistry toolRegistry;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public List<Tool> getAvailableTools(SessionEntity session) {
        if (session.getEnabledTools() == null || session.getEnabledTools().isBlank()) {
            return List.of();
        }
        List<String> enabledNames = Arrays.stream(session.getEnabledTools().split(","))
                .map(String::trim)
                .map(String::toLowerCase)
                .toList();

        return toolRegistry.getAllTools().stream()
                .filter(tool -> enabledNames.contains(tool.getName().toLowerCase()))
                .toList();
    }

    public String formatToolsDescription(List<Tool> tools) {
        if (tools.isEmpty()) {
            return "No tools available.";
        }
        StringBuilder sb = new StringBuilder();
        for (Tool tool : tools) {
            sb.append("- ").append(tool.getName()).append(": ").append(tool.getDescription()).append("\n");
            sb.append("  Parameter schema: ").append(tool.getParameterSchema()).append("\n");
        }
        return sb.toString();
    }

    public String buildReActSystemPrompt(String customSystemPrompt, String toolsDescription) {
        String basePrompt = """
                You are a ReAct AI chat agent. You solve problems by thinking step-by-step and using tools.
                
                You have access to the following tools:
                %s
                
                You MUST respond with a single valid JSON object matching the following schema:
                {
                  "thought": "Your step-by-step reasoning about what to do next.",
                  "toolCall": {
                    "name": "The name of the tool to call (or null if no tool is needed)",
                    "arguments": "The input arguments for the tool as a string (or null if no tool is needed)"
                  },
                  "finalAnswer": "The final answer to the user's query (or null if you are calling a tool)"
                }
                
                Rules:
                1. If you need to use a tool, set "toolCall" with the tool's name and arguments, and set "finalAnswer" to null.
                2. If you do not need to use a tool, or if you have gathered enough information from tool observations, set "toolCall" to null and provide the "finalAnswer".
                3. Output ONLY the JSON object. Do not wrap it in markdown code blocks (like ```json ... ```) or include any other text.
                """;

        String formattedBase = String.format(basePrompt, toolsDescription);
        if (customSystemPrompt != null && !customSystemPrompt.isBlank()) {
            return customSystemPrompt + "\n\n" + formattedBase;
        }
        return formattedBase;
    }

    public AgentDecision parseDecision(String text) {
        if (text == null || text.isBlank()) {
            return new AgentDecision("No response from LLM", null, "No response generated by the model.");
        }
        
        String cleaned = text.trim();
        // Strip markdown code blocks if the LLM ignored instructions and wrapped it anyway
        if (cleaned.startsWith("```")) {
            cleaned = cleaned.replaceAll("^```(?:json)?\\s*", "");
            cleaned = cleaned.replaceAll("\\s*```$", "");
            cleaned = cleaned.trim();
        }

        try {
            return objectMapper.readValue(cleaned, AgentDecision.class);
        } catch (Exception e) {
            log.warn("Failed to parse LLM response as JSON: {}. Response was: {}", e.getMessage(), text);
            // Fallback: try to extract JSON if there is extra text around it
            try {
                int start = cleaned.indexOf('{');
                int end = cleaned.lastIndexOf('}');
                if (start != -1 && end != -1 && end > start) {
                    String jsonSubstring = cleaned.substring(start, end + 1);
                    return objectMapper.readValue(jsonSubstring, AgentDecision.class);
                }
            } catch (Exception ex) {
                log.warn("Fallback JSON extraction also failed: {}", ex.getMessage());
            }
            // If all parsing fails, treat the entire response as the final answer
            return new AgentDecision("Failed to parse structured response", null, text);
        }
    }
}
